apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/gogs-data
    server: ose-master
