apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-git-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/gogs-git
    server: ose-master
